name: Build Capacitor Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Sync Capacitor ke Android
        run: node node_modules/@capacitor/cli/bin/capacitor sync android

      - name: Build APK Menggunakan Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Pindahkan dan Sediakan Link Download APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Barcode-Capacitor
          path: android/app/build/outputs/apk/debug/app-debug.apk